import { Person } from "./person";

export const PERSON : Person[] = [
    {"id":1,
    "firstname":"meet",
    "middlename":"sanjaykumar",
    "lastname":"patel",
    "gender": "male",
    "mobile" : "1023564897",
    "whatsapp" : "1023564789",
    "email" : "meetpatel21199@gmail.com",
    "occupation" : "developer",
    "address" : "",
    "city" : "vadodara",
    "area" : "manjalpur",
    "state" : "gujarat",
    "country" : "India",
    "pincode" : "391135",
    "dob" : "1-1-1999",
    "maritalstatus" : "unmarried",
    "dom" : "",
    "photo": "photo url...",
    //"society": new Society(1,"patel","patel samaj")
    "societyId": 1
  },
  {"id":2,
  "firstname":"mirank",
  "middlename":"rudrakumar",
  "lastname":"patel",
  "gender": "male",
  "mobile" : "1023564897",
  "whatsapp" : "1023564789",
  "email" : "mirankpatel21199@gmail.com",
  "occupation" : "developer",
  "address" : "",
  "city" : "vadodara",
  "area" : "akota",
  "state" : "gujarat",
  "country" : "India",
  "pincode" : "391135",
  "dob" : "1-1-1999",
  "maritalstatus" : "unmarried",
  "dom" : "",
  "photo": "photo url...",
  //"society": new Society(2,"bhagat","bhagat samaj")
  "societyId": 2
  },
  {"id":3,
    "firstname":"rudra",
    "middlename":"mirankkumar",
    "lastname":"patel",
    "gender": "male",
    "mobile" : "1023564897",
    "whatsapp" : "1023564789",
    "email" : "meetpatel21199@gmail.com",
    "occupation" : "developer",
    "address" : "",
    "city" : "vadodara",
    "area" : "dabhoi",
    "state" : "gujarat",
    "country" : "India",
    "pincode" : "391135",
    "dob" : "1-1-1999",
    "maritalstatus" : "unmarried",
    "dom" : "",
    "photo": "photo url...",
    //"society": new Society(1,"brahman","brahman samaj")
    "societyId": 3
  },
  ];